import { TourPackage } from '@/types';

export const tourPackages: TourPackage[] = [
  // Domestic Tours
  {
    id: 'gorilla-trekking',
    title: 'Gorilla Trekking Adventure',
    destination: 'Bwindi Impenetrable Forest',
    duration: '3 Days / 2 Nights',
    price: 'From $700 per person',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&h=800&fit=crop',
    galleryImages: [
      'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&h=800&fit=crop',
    ],
    description: 'Experience the majestic mountain gorillas in their natural habitat. This once-in-a-lifetime adventure takes you deep into the Bwindi Impenetrable Forest, home to half of the world\'s remaining mountain gorilla population.',
    highlights: [
      'Gorilla trekking permit included',
      'Professional guide',
      'Lodge accommodation',
      'All meals included',
      'Transportation',
    ],
    type: 'domestic',
    category: 'Wildlife',
    difficulty: 'Challenging',
    bestTimeToVisit: 'June-August and December-February (dry seasons)',
    groupSize: 'Small groups (2-8 people)',
    maxAltitude: '2,607 m (8,551 ft)',
    physicalRequirements: 'Moderate to good fitness level. Trekking involves steep terrain and can take 2-8 hours. Participants should be able to walk for extended periods at high altitude.',
    whyChooseThis: [
      'See 50% of the world\'s remaining mountain gorillas',
      'Expert naturalist guides with decades of experience',
      'Small group sizes ensure intimate wildlife encounters',
      'Comfortable eco-lodges with stunning views',
      'Commitment to conservation and community support',
      'Flexible itineraries based on gorilla movements',
    ],
    rating: 4.9,
    reviewCount: 247,
    seasonalInfo: 'Best visited during dry seasons. December-February offers sunny days; June-August is lush and green. Avoid rainy seasons (March-May, September-November).',
    pricingTiers: [
      {
        name: 'Standard',
        pricePerPerson: 700,
        description: 'Comfortable lodge accommodation with basic amenities',
        features: ['3-star lodge', 'Shared bathroom', 'Basic meals'],
      },
      {
        name: 'Premium',
        pricePerPerson: 1200,
        description: 'Upscale lodge with enhanced comfort and amenities',
        features: ['4-star lodge', 'Private bathroom', 'Fine dining meals'],
      },
      {
        name: 'Luxury',
        pricePerPerson: 1800,
        description: 'Exclusive eco-resort experience with premium services',
        features: ['5-star resort', 'Suite accommodation', 'Gourmet meals', 'Spa services'],
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival and Briefing',
        activities: [
          'Pickup from Entebbe/Kampala airport',
          'Scenic drive to Bwindi (8-9 hours)',
          'Lunch en route',
          'Check-in at lodge',
          'Evening briefing about gorilla trekking',
          'Dinner and overnight at lodge',
        ],
        meals: 'Lunch & Dinner',
        accommodation: 'Bwindi Impenetrable Forest Lodge',
      },
      {
        day: 2,
        title: 'Gorilla Trekking Day',
        activities: [
          'Early breakfast',
          'Transfer to park headquarters',
          'Pre-trekking briefing',
          'Gorilla trekking (2-8 hours depending on gorilla location)',
          '1 hour with gorillas',
          'Return to lodge',
          'Lunch and rest',
          'Optional community walk',
          'Dinner and overnight',
        ],
        meals: 'Breakfast, Lunch & Dinner',
        accommodation: 'Bwindi Impenetrable Forest Lodge',
      },
      {
        day: 3,
        title: 'Departure',
        activities: [
          'Breakfast',
          'Check-out',
          'Return journey to Entebbe/Kampala',
          'Lunch en route',
          'Drop-off at airport or hotel',
        ],
        meals: 'Breakfast & Lunch',
      },
    ],
    costBreakdown: {
      included: [
        'Gorilla trekking permit ($700)',
        'Accommodation (2 nights)',
        'All meals',
        'Transportation',
        'Professional guide',
        'Park fees',
      ],
      excluded: [
        'International flights',
        'Visa fees',
        'Travel insurance',
        'Tips and gratuities',
        'Personal expenses',
        'Alcoholic beverages',
      ],
    },
  },
  {
    id: 'queen-elizabeth-safari',
    title: 'Queen Elizabeth Safari',
    destination: 'Queen Elizabeth National Park',
    duration: '4 Days / 3 Nights',
    price: 'From $600 per person',
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&h=800&fit=crop',
    galleryImages: [
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&h=800&fit=crop',
    ],
    description: 'Wildlife safari in one of Uganda\'s most beautiful national parks. Spot elephants, lions, hippos, and over 600 bird species in their natural habitat.',
    highlights: [
      'Game drives',
      'Boat cruise on Kazinga Channel',
      'Bird watching',
      'Lodge accommodation',
      'All meals included',
    ],
    type: 'domestic',
    category: 'Wildlife',
    difficulty: 'Easy',
    bestTimeToVisit: 'Year-round (best June-August and December-February)',
    groupSize: 'Small groups (2-12 people)',
    maxAltitude: '621 m (2,037 ft)',
    physicalRequirements: 'Easy. Minimal walking required. Game drives from open-sided vehicles. Suitable for all fitness levels including families and seniors.',
    whyChooseThis: [
      'Home to 95 mammal species and over 600 bird species',
      'Year-round wildlife viewing opportunities',
      'Stunning Kazinga Channel boat cruises with abundant hippos',
      'Expert wildlife photographers guide available',
      'Comfortable mid-range and luxury lodge options',
      'Perfect for families and first-time safari-goers',
    ],
    rating: 4.8,
    reviewCount: 198,
    seasonalInfo: 'Open year-round. Rainy seasons (April-May, October-November) offer lush landscapes with fewer tourists. Dry seasons provide clearer sightings.',
    pricingTiers: [
      {
        name: 'Explorer',
        pricePerPerson: 600,
        description: 'Cozy mid-range lodge with essential amenities',
        features: ['3-star lodge', 'Twin/double rooms', 'Shared facilities'],
      },
      {
        name: 'Safari Pro',
        pricePerPerson: 950,
        description: 'Premium lodge experience with better views',
        features: ['4-star lodge', 'Private bathroom', 'Better meal plans'],
      },
      {
        name: 'Luxury Explorer',
        pricePerPerson: 1500,
        description: 'Exclusive wildlife experience with premium service',
        features: ['5-star resort', 'Riverside suites', 'Private guide option'],
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival and Evening Game Drive',
        activities: [
          'Pickup from Entebbe/Kampala',
          'Drive to Queen Elizabeth National Park',
          'Lunch en route',
          'Check-in at lodge',
          'Evening game drive',
          'Dinner and overnight',
        ],
        meals: 'Lunch & Dinner',
        accommodation: 'Queen Elizabeth Safari Lodge',
      },
      {
        day: 2,
        title: 'Morning Game Drive and Boat Cruise',
        activities: [
          'Early morning game drive',
          'Breakfast at lodge',
          'Boat cruise on Kazinga Channel (2 hours)',
          'Lunch',
          'Afternoon game drive',
          'Dinner and overnight',
        ],
        meals: 'Breakfast, Lunch & Dinner',
        accommodation: 'Queen Elizabeth Safari Lodge',
      },
      {
        day: 3,
        title: 'Chimpanzee Tracking',
        activities: [
          'Early breakfast',
          'Chimpanzee tracking in Kyambura Gorge',
          'Lunch',
          'Cultural visit to local community',
          'Dinner and overnight',
        ],
        meals: 'Breakfast, Lunch & Dinner',
        accommodation: 'Queen Elizabeth Safari Lodge',
      },
      {
        day: 4,
        title: 'Departure',
        activities: [
          'Breakfast',
          'Check-out',
          'Return journey',
          'Lunch en route',
          'Drop-off',
        ],
        meals: 'Breakfast & Lunch',
      },
    ],
    costBreakdown: {
      included: [
        'Park entry fees',
        'Accommodation (3 nights)',
        'All meals',
        'Game drives',
        'Boat cruise',
        'Transportation',
        'Professional guide',
      ],
      excluded: [
        'Chimpanzee tracking permit ($50)',
        'International flights',
        'Visa fees',
        'Travel insurance',
        'Tips',
        'Personal expenses',
      ],
    },
  },
  {
    id: 'murchison-falls',
    title: 'Murchison Falls Experience',
    destination: 'Murchison Falls National Park',
    duration: '3 Days / 2 Nights',
    price: 'From $550 per person',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop',
    galleryImages: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&h=800&fit=crop',
    ],
    description: 'Witness the powerful Murchison Falls where the Nile River forces its way through a narrow gorge. Experience incredible wildlife viewing and scenic beauty.',
    highlights: [
      'Murchison Falls visit',
      'Wildlife viewing',
      'Nile boat cruise',
      'Safari lodge accommodation',
      'Game drives',
    ],
    type: 'domestic',
    category: 'Wildlife',
    difficulty: 'Moderate',
    bestTimeToVisit: 'June-August and December-February',
    groupSize: 'Small groups (2-10 people)',
    maxAltitude: '938 m (3,077 ft)',
    physicalRequirements: 'Moderate fitness. Mix of vehicle travel and short walks. Some trails to Murchison Falls may be steep.',
    whyChooseThis: [
      'One of Africa\'s most powerful waterfalls',
      'Exceptional wildlife diversity including lions and buffalo',
      'Dramatic landscapes along the Nile River',
      'Peaceful boat cruises with river wildlife',
      'Fewer tourists than other parks',
      'Professional naturalist guides',
    ],
    rating: 4.7,
    reviewCount: 162,
    seasonalInfo: 'Dry seasons (June-August, December-February) offer best game viewing. Green season (March-May) showcases lush vegetation and fewer visitors.',
    pricingTiers: [
      {
        name: 'Budget Safari',
        pricePerPerson: 550,
        description: 'Basic safari lodge with comfortable rooms',
        features: ['3-star lodge', 'Standard rooms', 'Basic amenities'],
      },
      {
        name: 'Standard Safari',
        pricePerPerson: 850,
        description: 'Mid-range lodge with good facilities',
        features: ['4-star lodge', 'En-suite bathrooms', 'Full meal plan'],
      },
      {
        name: 'Premium Safari',
        pricePerPerson: 1300,
        description: 'Luxury safari experience with river views',
        features: ['5-star lodge', 'Deluxe rooms', 'Fine dining'],
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Journey to Murchison Falls',
        activities: [
          'Pickup from Entebbe/Kampala',
          'Drive to Murchison Falls (5-6 hours)',
          'Lunch en route',
          'Check-in at lodge',
          'Evening game drive',
          'Dinner and overnight',
        ],
        meals: 'Lunch & Dinner',
        accommodation: 'Murchison Falls Safari Lodge',
      },
      {
        day: 2,
        title: 'Falls Visit and Boat Cruise',
        activities: [
          'Early breakfast',
          'Morning game drive',
          'Visit to top of Murchison Falls',
          'Boat cruise to bottom of falls',
          'Lunch',
          'Afternoon game drive',
          'Dinner and overnight',
        ],
        meals: 'Breakfast, Lunch & Dinner',
        accommodation: 'Murchison Falls Safari Lodge',
      },
      {
        day: 3,
        title: 'Departure',
        activities: [
          'Breakfast',
          'Final game drive',
          'Check-out',
          'Return journey',
          'Lunch en route',
          'Drop-off',
        ],
        meals: 'Breakfast & Lunch',
      },
    ],
    costBreakdown: {
      included: [
        'Park entry fees',
        'Accommodation (2 nights)',
        'All meals',
        'Game drives',
        'Boat cruise',
        'Transportation',
        'Guide services',
      ],
      excluded: [
        'International flights',
        'Visa fees',
        'Travel insurance',
        'Tips',
        'Personal expenses',
      ],
    },
  },
  {
    id: 'chimpanzee-trekking',
    title: 'Chimpanzee Trekking',
    destination: 'Kibale Forest National Park',
    duration: '2 Days / 1 Night',
    price: 'From $400 per person',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&h=800&fit=crop',
    galleryImages: [
      'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop',
    ],
    description: 'Track our closest relatives in the wild. Kibale Forest is home to the highest concentration of primates in Africa, including over 1,500 chimpanzees.',
    highlights: [
      'Chimpanzee tracking permit',
      'Nature walks',
      'Eco-lodge accommodation',
      'Bird watching',
      'All meals included',
    ],
    type: 'domestic',
    category: 'Wildlife',
    difficulty: 'Moderate',
    bestTimeToVisit: 'June-August and December-February',
    groupSize: 'Small groups (2-8 people)',
    maxAltitude: '1,600 m (5,249 ft)',
    physicalRequirements: 'Moderate hiking. Trail can be steep and muddy. Requires moderate to good fitness. Tracking can last 2-4 hours.',
    whyChooseThis: [
      'Highest concentration of chimpanzees in Africa',
      'Experience intimate encounters with wild chimps',
      'Pristine rainforest ecosystem',
      'Excellent birdwatching opportunities',
      'Knowledgeable and passionate local guides',
      'The authentic "Chimpanzee tracking" experience',
    ],
    rating: 4.9,
    reviewCount: 187,
    seasonalInfo: 'Best from June-August (cooler) and December-February (dry season). May receive high rainfall but offers lush forest and fewer tourists.',
    pricingTiers: [
      {
        name: 'Basic Tracker',
        pricePerPerson: 400,
        description: 'Eco-lodge with basic amenities and shared facilities',
        features: ['Eco-lodge', 'Twin rooms', 'Local meals'],
      },
      {
        name: 'Nature Lodge',
        pricePerPerson: 700,
        description: 'Comfortable lodge with private facilities',
        features: ['3-star lodge', 'Private bathroom', 'Quality meals'],
      },
      {
        name: 'Luxury Forest Retreat',
        pricePerPerson: 1100,
        description: 'Premium forest resort with full services',
        features: ['4-star resort', 'Deluxe accommodation', 'Gourmet meals'],
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival and Briefing',
        activities: [
          'Pickup from Entebbe/Kampala',
          'Drive to Kibale Forest (5-6 hours)',
          'Lunch en route',
          'Check-in at eco-lodge',
          'Evening nature walk',
          'Briefing about chimpanzee tracking',
          'Dinner and overnight',
        ],
        meals: 'Lunch & Dinner',
        accommodation: 'Kibale Forest Eco-Lodge',
      },
      {
        day: 2,
        title: 'Chimpanzee Tracking and Departure',
        activities: [
          'Early breakfast',
          'Chimpanzee tracking (2-4 hours)',
          '1 hour with chimpanzees',
          'Return to lodge',
          'Lunch',
          'Check-out',
          'Return journey',
          'Drop-off',
        ],
        meals: 'Breakfast & Lunch',
        accommodation: 'Kibale Forest Eco-Lodge',
      },
    ],
    costBreakdown: {
      included: [
        'Chimpanzee tracking permit ($200)',
        'Accommodation (1 night)',
        'All meals',
        'Transportation',
        'Professional guide',
        'Park fees',
      ],
      excluded: [
        'International flights',
        'Visa fees',
        'Travel insurance',
        'Tips',
        'Personal expenses',
        'Optional activities',
      ],
    },
  },
  {
    id: 'rwenzori-mountains',
    title: 'Rwenzori Mountains Hike',
    destination: 'Rwenzori Mountains National Park',
    duration: '5 Days / 4 Nights',
    price: 'From $800 per person',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop',
    galleryImages: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&h=800&fit=crop',
    ],
    description: 'Conquer the "Mountains of the Moon" - Africa\'s third highest peak. Experience stunning alpine scenery, unique flora, and challenging mountain terrain.',
    highlights: [
      'Mountain climbing',
      'Scenic views',
      'Camping accommodation',
      'Professional mountain guides',
      'Porters included',
    ],
    type: 'domestic',
    category: 'Adventure',
    difficulty: 'Challenging',
    bestTimeToVisit: 'June-August and December-February (dry seasons)',
    groupSize: 'Small groups (4-8 people)',
    maxAltitude: '5,109 m (16,763 ft)',
    physicalRequirements: 'Excellent fitness required. High altitude trekking with long daily walks (6-8 hours). Altitude acclimatization essential. Not suitable for beginners.',
    whyChooseThis: [
      'Africa\'s third highest mountain with glaciers',
      'Unique alpine ecosystem with rare flora',
      'Small group sizes for personalized experience',
      'Professional mountain guides with rescue certification',
      'Porters handle all equipment',
      'Summit certificate awarded',
    ],
    rating: 4.6,
    reviewCount: 89,
    seasonalInfo: 'Best June-August (dry, clear weather) and December-February. Avoid April-May and September-November rainy seasons.',
    pricingTiers: [
      {
        name: 'Standard Trek',
        pricePerPerson: 800,
        description: 'Basic mountain camping experience',
        features: ['Camping accommodation', 'Standard meals', 'Basic guides'],
      },
      {
        name: 'Premium Trek',
        pricePerPerson: 1200,
        description: 'Enhanced comfort with better meals',
        features: ['Camping with better tents', 'Quality meals', 'Expert guides'],
      },
      {
        name: 'VIP Summit',
        pricePerPerson: 1600,
        description: 'Luxury mountain experience with maximum support',
        features: ['Premium camping', 'Gourmet meals', 'Lead guide + assistant'],
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival and Start of Trek',
        activities: [
          'Pickup from Kasese',
          'Transfer to park headquarters',
          'Briefing and equipment check',
          'Start trek to Nyabitaba Hut',
          'Camping and dinner',
        ],
        meals: 'Lunch & Dinner',
        accommodation: 'Nyabitaba Hut Camp',
      },
      {
        day: 2,
        title: 'Ascend to John Matte Hut',
        activities: [
          'Early breakfast',
          'Continue ascent',
          'Cross Bujuku River',
          'Reach John Matte Hut',
          'Camping and dinner',
        ],
        meals: 'Breakfast, Lunch & Dinner',
        accommodation: 'John Matte Hut Camp',
      },
      {
        day: 3,
        title: 'Reach Bujuku Lake',
        activities: [
          'Breakfast',
          'Trek to Bujuku Lake',
          'Scenic views of glaciers',
          'Camping at Bujuku Hut',
          'Dinner',
        ],
        meals: 'Breakfast, Lunch & Dinner',
        accommodation: 'Bujuku Hut Camp',
      },
      {
        day: 4,
        title: 'Summit Attempt',
        activities: [
          'Early morning summit attempt',
          'Reach Margherita Peak (5,109m)',
          'Descend to Kitandara Hut',
          'Camping and dinner',
        ],
        meals: 'Breakfast, Lunch & Dinner',
        accommodation: 'Kitandara Hut Camp',
      },
      {
        day: 5,
        title: 'Descent and Departure',
        activities: [
          'Breakfast',
          'Final descent',
          'Return to park headquarters',
          'Certificate presentation',
          'Transfer back',
        ],
        meals: 'Breakfast & Lunch',
      },
    ],
    costBreakdown: {
      included: [
        'Park entry fees',
        'Mountain climbing permit',
        'Camping accommodation',
        'All meals',
        'Professional guides',
        'Porters',
        'Camping equipment',
      ],
      excluded: [
        'Personal hiking gear',
        'International flights',
        'Visa fees',
        'Travel insurance',
        'Tips',
        'Personal expenses',
      ],
    },
  },
  // International Tours
  {
    id: 'dubai-campus-vibe',
    title: 'Dubai Campus Vibe',
    destination: 'Dubai, UAE',
    duration: '5 Days / 4 Nights',
    price: 'From $1,200 per person',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&h=800&fit=crop',
    description: 'A special Dubai experience designed for university students: vibrant campus life, city exploration, and youth-focused activities.',
    galleryImages: [
      'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&h=800&fit=crop',
    ],
    highlights: [
      'Burj Khalifa visit',
      'Desert safari',
      'Shopping tours',
      'Luxury hotels',
      'Dhow cruise',
    ],
    type: 'international',
    category: 'City Tour',
    difficulty: 'Easy',
    bestTimeToVisit: 'October-April (mild weather)',
    groupSize: 'All group sizes (2-50+)',
    physicalRequirements: 'Easy. Mostly vehicle and walking tours. No strenuous activities. Suitable for families and seniors.',
    whyChooseThis: [
      'World\'s tallest building (Burj Khalifa)',
      'Luxury shopping and dining',
      'Authentic desert safari experience',
      'Perfect blend of modern and traditional',
      'Year-round sunny weather',
      'Safe and well-developed tourist infrastructure',
    ],
    rating: 4.8,
    reviewCount: 324,
    seasonalInfo: 'Best October-April with pleasant 25-30°C weather. May-September is extremely hot (40°C+).',
    pricingTiers: [
      {
        name: 'City Explorer',
        pricePerPerson: 1200,
        description: 'Standard city tour experience',
        features: ['4-star hotel', 'Main attractions', 'Group tours'],
      },
      {
        name: 'Luxury Dubai',
        pricePerPerson: 1800,
        description: 'Premium experience with upscale hotels',
        features: ['5-star hotel', 'VIP tours', 'Private guide option'],
      },
      {
        name: 'Ultimate Dubai',
        pricePerPerson: 2500,
        description: 'All-inclusive luxury with exclusive experiences',
        features: ['Burj Khalifa suite view', 'Private guide', 'Fine dining included'],
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Dubai',
        activities: [
          'Airport pickup',
          'Transfer to hotel',
          'Check-in',
          'Evening Dhow cruise with dinner',
          'Overnight at hotel',
        ],
        meals: 'Dinner',
        accommodation: 'Luxury Dubai Hotel',
      },
      {
        day: 2,
        title: 'City Tour and Burj Khalifa',
        activities: [
          'Breakfast at hotel',
          'Dubai city tour',
          'Visit Burj Khalifa (124th floor)',
          'Dubai Mall visit',
          'Lunch',
          'Evening at leisure',
          'Overnight',
        ],
        meals: 'Breakfast, Lunch & Dinner',
        accommodation: 'Luxury Dubai Hotel',
      },
      {
        day: 3,
        title: 'Desert Safari',
        activities: [
          'Breakfast',
          'Morning at leisure',
          'Afternoon desert safari',
          'Camel riding',
          'BBQ dinner and entertainment',
          'Return to hotel',
        ],
        meals: 'Breakfast, Lunch & Dinner',
        accommodation: 'Luxury Dubai Hotel',
      },
      {
        day: 4,
        title: 'Shopping and Leisure',
        activities: [
          'Breakfast',
          'Shopping at Gold Souk and Spice Souk',
          'Dubai Marina visit',
          'Lunch',
          'Palm Jumeirah tour',
          'Evening at leisure',
        ],
        meals: 'Breakfast, Lunch & Dinner',
        accommodation: 'Luxury Dubai Hotel',
      },
      {
        day: 5,
        title: 'Departure',
        activities: [
          'Breakfast',
          'Check-out',
          'Transfer to airport',
          'Departure',
        ],
        meals: 'Breakfast',
      },
    ],
    costBreakdown: {
      included: [
        'Return flights (from Entebbe)',
        'Hotel accommodation (4 nights)',
        'Daily breakfast',
        'Dhow cruise dinner',
        'Desert safari',
        'Burj Khalifa tickets',
        'City tour',
        'Airport transfers',
      ],
      excluded: [
        'Visa fees',
        'Lunch and dinner (except specified)',
        'Travel insurance',
        'Tips',
        'Personal expenses',
        'Shopping',
      ],
    },
  },
  {
    id: 'paris-london',
    title: 'Paris & London',
    destination: 'Paris, France & London, UK',
    duration: '7 Days / 6 Nights',
    price: 'From $2,500 per person',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&h=800&fit=crop',
    galleryImages: [
      'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1529655683826-aba9b3e77383?w=1200&h=800&fit=crop',
    ],
    description: 'Experience two of Europe\'s most iconic cities. From the Eiffel Tower to Big Ben, discover the best of Paris and London.',
    highlights: [
      'Eiffel Tower visit',
      'Louvre Museum',
      'Big Ben and Westminster',
      'Thames River cruise',
      'Eurostar train journey',
    ],
    type: 'international',
    category: 'City Tour',
    difficulty: 'Easy',
    bestTimeToVisit: 'April–October (mild weather, long days)',
    groupSize: 'Small groups (2–12)',
    rating: 4.9,
    reviewCount: 287,
    whyChooseThis: [
      'Two iconic European capitals in one trip',
      'Scenic Eurostar train journey through the Channel',
      'Curated mix of art, history, and culture',
      'Central hotels for easy exploration',
      'Museum passes and city tours included',
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Paris',
        activities: [
          'Airport pickup',
          'Transfer to hotel',
          'Check-in',
          'Evening Seine River cruise',
          'Dinner',
          'Overnight',
        ],
      },
      {
        day: 2,
        title: 'Paris City Tour',
        activities: [
          'Breakfast',
          'Eiffel Tower visit',
          'Louvre Museum',
          'Lunch',
          'Notre-Dame Cathedral',
          'Champs-Élysées walk',
          'Dinner',
        ],
      },
      {
        day: 3,
        title: 'Versailles and More',
        activities: [
          'Breakfast',
          'Day trip to Palace of Versailles',
          'Lunch',
          'Return to Paris',
          'Evening at leisure',
        ],
      },
      {
        day: 4,
        title: 'Travel to London',
        activities: [
          'Breakfast',
          'Check-out',
          'Eurostar to London',
          'Hotel check-in',
          'Evening Thames cruise',
          'Dinner',
        ],
      },
      {
        day: 5,
        title: 'London City Tour',
        activities: [
          'Breakfast',
          'Big Ben and Westminster',
          'Buckingham Palace',
          'Tower of London',
          'Lunch',
          'British Museum',
          'Dinner',
        ],
      },
      {
        day: 6,
        title: 'London Exploration',
        activities: [
          'Breakfast',
          'Hyde Park',
          'Shopping at Oxford Street',
          'Lunch',
          'London Eye',
          'Evening show (optional)',
        ],
      },
      {
        day: 7,
        title: 'Departure',
        activities: [
          'Breakfast',
          'Check-out',
          'Transfer to airport',
          'Departure',
        ],
      },
    ],
    costBreakdown: {
      included: [
        'Return flights (from Entebbe)',
        'Hotel accommodation (6 nights)',
        'Daily breakfast',
        'Eurostar tickets',
        'City tours',
        'Museum entries',
        'Airport transfers',
      ],
      excluded: [
        'Schengen visa',
        'UK visa',
        'Lunch and dinner',
        'Travel insurance',
        'Tips',
        'Personal expenses',
      ],
    },
  },
  {
    id: 'cape-town',
    title: 'Cape Town Adventure',
    destination: 'Cape Town, South Africa',
    duration: '6 Days / 5 Nights',
    price: 'From $1,800 per person',
    image: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=1200&h=800&fit=crop',
    description: 'Discover the beauty of Cape Town - from Table Mountain to wine country, penguin beaches to safari adventures.',
    highlights: [
      'Table Mountain',
      'Wine tours',
      'Penguin Beach',
      'Safari experience',
      'Cape of Good Hope',
    ],
    type: 'international',
    category: 'Adventure',
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Cape Town',
        activities: [
          'Airport pickup',
          'Transfer to hotel',
          'Check-in',
          'V&A Waterfront visit',
          'Dinner',
          'Overnight',
        ],
      },
      {
        day: 2,
        title: 'Table Mountain and City Tour',
        activities: [
          'Breakfast',
          'Table Mountain cable car',
          'City tour',
          'Lunch',
          'Robben Island tour',
          'Dinner',
        ],
      },
      {
        day: 3,
        title: 'Cape Peninsula Tour',
        activities: [
          'Breakfast',
          'Cape of Good Hope',
          'Boulders Beach (Penguins)',
          'Lunch',
          'Chapman\'s Peak Drive',
          'Return to hotel',
        ],
      },
      {
        day: 4,
        title: 'Wine Country',
        activities: [
          'Breakfast',
          'Stellenbosch wine tour',
          'Wine tasting',
          'Lunch at vineyard',
          'Return to Cape Town',
          'Dinner',
        ],
      },
      {
        day: 5,
        title: 'Safari Day Trip',
        activities: [
          'Early breakfast',
          'Full-day safari experience',
          'Lunch',
          'Wildlife viewing',
          'Return to hotel',
          'Dinner',
        ],
      },
      {
        day: 6,
        title: 'Departure',
        activities: [
          'Breakfast',
          'Check-out',
          'Transfer to airport',
          'Departure',
        ],
      },
    ],
    costBreakdown: {
      included: [
        'Return flights (from Entebbe)',
        'Hotel accommodation (5 nights)',
        'Daily breakfast',
        'Table Mountain tickets',
        'Wine tour',
        'Safari experience',
        'All tours',
        'Airport transfers',
      ],
      excluded: [
        'Visa fees',
        'Lunch and dinner',
        'Travel insurance',
        'Tips',
        'Personal expenses',
      ],
    },
  },
  {
    id: 'thailand-discovery',
    title: 'Thailand Discovery',
    destination: 'Bangkok & Phuket, Thailand',
    duration: '8 Days / 7 Nights',
    price: 'From $1,500 per person',
    image: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=1200&h=800&fit=crop',
    description: 'Experience the best of Thailand - from bustling Bangkok temples to pristine Phuket beaches.',
    highlights: [
      'Bangkok temples',
      'Beach resorts',
      'Floating markets',
      'Elephant sanctuary',
      'Thai cooking class',
    ],
    type: 'international',
    category: 'Beach & Culture',
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Bangkok',
        activities: [
          'Airport pickup',
          'Transfer to hotel',
          'Check-in',
          'Evening street food tour',
          'Overnight',
        ],
      },
      {
        day: 2,
        title: 'Bangkok Temples',
        activities: [
          'Breakfast',
          'Grand Palace',
          'Wat Pho (Reclining Buddha)',
          'Wat Arun',
          'Lunch',
          'Floating market',
          'Dinner',
        ],
      },
      {
        day: 3,
        title: 'Bangkok to Phuket',
        activities: [
          'Breakfast',
          'Check-out',
          'Flight to Phuket',
          'Hotel check-in',
          'Beach time',
          'Dinner',
        ],
      },
      {
        day: 4,
        title: 'Phuket Beach Day',
        activities: [
          'Breakfast',
          'Beach activities',
          'Water sports',
          'Lunch',
          'Spa treatment',
          'Dinner',
        ],
      },
      {
        day: 5,
        title: 'Island Hopping',
        activities: [
          'Breakfast',
          'Phi Phi Islands tour',
          'Snorkeling',
          'Lunch',
          'Beach time',
          'Return to hotel',
        ],
      },
      {
        day: 6,
        title: 'Elephant Sanctuary',
        activities: [
          'Breakfast',
          'Elephant sanctuary visit',
          'Thai cooking class',
          'Lunch',
          'Return to hotel',
          'Dinner',
        ],
      },
      {
        day: 7,
        title: 'Phuket to Bangkok',
        activities: [
          'Breakfast',
          'Check-out',
          'Flight to Bangkok',
          'Hotel check-in',
          'Shopping',
          'Farewell dinner',
        ],
      },
      {
        day: 8,
        title: 'Departure',
        activities: [
          'Breakfast',
          'Check-out',
          'Transfer to airport',
          'Departure',
        ],
      },
    ],
    costBreakdown: {
      included: [
        'Return flights (from Entebbe)',
        'Domestic flights',
        'Hotel accommodation (7 nights)',
        'Daily breakfast',
        'All tours',
        'Elephant sanctuary',
        'Cooking class',
        'Airport transfers',
      ],
      excluded: [
        'Visa fees',
        'Lunch and dinner',
        'Travel insurance',
        'Tips',
        'Personal expenses',
      ],
    },
  },
];

export interface ItineraryDay {
  day: number;
  title: string;
  activities: string[];
}

export interface CostBreakdown {
  included: string[];
  excluded: string[];
}

export interface TourPackageWithDetails extends TourPackage {
  itinerary: ItineraryDay[];
  costBreakdown: CostBreakdown;
}

