import { TourPackage } from '@/types';

export const tourPackages: TourPackage[] = [
  // Domestic Tours
  {
    id: 'gorilla-trekking',
    title: 'Gorilla Trekking Adventure',
    destination: 'Bwindi Impenetrable Forest',
    duration: '3 Days / 2 Nights',
    price: 'From $700 per person',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&h=800&fit=crop',
    description: 'Experience the majestic mountain gorillas in their natural habitat. This once-in-a-lifetime adventure takes you deep into the Bwindi Impenetrable Forest, home to half of the world\'s remaining mountain gorilla population.',
    highlights: [
      'Gorilla trekking permit included',
      'Professional guide',
      'Lodge accommodation',
      'All meals included',
      'Transportation',
    ],
    type: 'domestic',
    category: 'Wildlife',
    itinerary: [
      {
        day: 1,
        title: 'Arrival and Briefing',
        activities: [
          'Pickup from Entebbe/Kampala airport',
          'Scenic drive to Bwindi (8-9 hours)',
          'Lunch en route',
          'Check-in at lodge',
          'Evening briefing about gorilla trekking',
          'Dinner and overnight at lodge',
        ],
      },
      {
        day: 2,
        title: 'Gorilla Trekking Day',
        activities: [
          'Early breakfast',
          'Transfer to park headquarters',
          'Pre-trekking briefing',
          'Gorilla trekking (2-8 hours depending on gorilla location)',
          '1 hour with gorillas',
          'Return to lodge',
          'Lunch and rest',
          'Optional community walk',
          'Dinner and overnight',
        ],
      },
      {
        day: 3,
        title: 'Departure',
        activities: [
          'Breakfast',
          'Check-out',
          'Return journey to Entebbe/Kampala',
          'Lunch en route',
          'Drop-off at airport or hotel',
        ],
      },
    ],
    costBreakdown: {
      included: [
        'Gorilla trekking permit ($700)',
        'Accommodation (2 nights)',
        'All meals',
        'Transportation',
        'Professional guide',
        'Park fees',
      ],
      excluded: [
        'International flights',
        'Visa fees',
        'Travel insurance',
        'Tips and gratuities',
        'Personal expenses',
        'Alcoholic beverages',
      ],
    },
  },
  {
    id: 'queen-elizabeth-safari',
    title: 'Queen Elizabeth Safari',
    destination: 'Queen Elizabeth National Park',
    duration: '4 Days / 3 Nights',
    price: 'From $600 per person',
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&h=800&fit=crop',
    description: 'Wildlife safari in one of Uganda\'s most beautiful national parks. Spot elephants, lions, hippos, and over 600 bird species in their natural habitat.',
    highlights: [
      'Game drives',
      'Boat cruise on Kazinga Channel',
      'Bird watching',
      'Lodge accommodation',
      'All meals included',
    ],
    type: 'domestic',
    category: 'Wildlife',
    itinerary: [
      {
        day: 1,
        title: 'Arrival and Evening Game Drive',
        activities: [
          'Pickup from Entebbe/Kampala',
          'Drive to Queen Elizabeth National Park',
          'Lunch en route',
          'Check-in at lodge',
          'Evening game drive',
          'Dinner and overnight',
        ],
      },
      {
        day: 2,
        title: 'Morning Game Drive and Boat Cruise',
        activities: [
          'Early morning game drive',
          'Breakfast at lodge',
          'Boat cruise on Kazinga Channel (2 hours)',
          'Lunch',
          'Afternoon game drive',
          'Dinner and overnight',
        ],
      },
      {
        day: 3,
        title: 'Chimpanzee Tracking',
        activities: [
          'Early breakfast',
          'Chimpanzee tracking in Kyambura Gorge',
          'Lunch',
          'Cultural visit to local community',
          'Dinner and overnight',
        ],
      },
      {
        day: 4,
        title: 'Departure',
        activities: [
          'Breakfast',
          'Check-out',
          'Return journey',
          'Lunch en route',
          'Drop-off',
        ],
      },
    ],
    costBreakdown: {
      included: [
        'Park entry fees',
        'Accommodation (3 nights)',
        'All meals',
        'Game drives',
        'Boat cruise',
        'Transportation',
        'Professional guide',
      ],
      excluded: [
        'Chimpanzee tracking permit ($50)',
        'International flights',
        'Visa fees',
        'Travel insurance',
        'Tips',
        'Personal expenses',
      ],
    },
  },
  {
    id: 'murchison-falls',
    title: 'Murchison Falls Experience',
    destination: 'Murchison Falls National Park',
    duration: '3 Days / 2 Nights',
    price: 'From $550 per person',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop',
    description: 'Witness the powerful Murchison Falls where the Nile River forces its way through a narrow gorge. Experience incredible wildlife viewing and scenic beauty.',
    highlights: [
      'Murchison Falls visit',
      'Wildlife viewing',
      'Nile boat cruise',
      'Safari lodge accommodation',
      'Game drives',
    ],
    type: 'domestic',
    category: 'Wildlife',
    itinerary: [
      {
        day: 1,
        title: 'Journey to Murchison Falls',
        activities: [
          'Pickup from Entebbe/Kampala',
          'Drive to Murchison Falls (5-6 hours)',
          'Lunch en route',
          'Check-in at lodge',
          'Evening game drive',
          'Dinner and overnight',
        ],
      },
      {
        day: 2,
        title: 'Falls Visit and Boat Cruise',
        activities: [
          'Early breakfast',
          'Morning game drive',
          'Visit to top of Murchison Falls',
          'Boat cruise to bottom of falls',
          'Lunch',
          'Afternoon game drive',
          'Dinner and overnight',
        ],
      },
      {
        day: 3,
        title: 'Departure',
        activities: [
          'Breakfast',
          'Final game drive',
          'Check-out',
          'Return journey',
          'Lunch en route',
          'Drop-off',
        ],
      },
    ],
    costBreakdown: {
      included: [
        'Park entry fees',
        'Accommodation (2 nights)',
        'All meals',
        'Game drives',
        'Boat cruise',
        'Transportation',
        'Guide services',
      ],
      excluded: [
        'International flights',
        'Visa fees',
        'Travel insurance',
        'Tips',
        'Personal expenses',
      ],
    },
  },
  {
    id: 'chimpanzee-trekking',
    title: 'Chimpanzee Trekking',
    destination: 'Kibale Forest National Park',
    duration: '2 Days / 1 Night',
    price: 'From $400 per person',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&h=800&fit=crop',
    description: 'Track our closest relatives in the wild. Kibale Forest is home to the highest concentration of primates in Africa, including over 1,500 chimpanzees.',
    highlights: [
      'Chimpanzee tracking permit',
      'Nature walks',
      'Eco-lodge accommodation',
      'Bird watching',
      'All meals included',
    ],
    type: 'domestic',
    category: 'Wildlife',
    itinerary: [
      {
        day: 1,
        title: 'Arrival and Briefing',
        activities: [
          'Pickup from Entebbe/Kampala',
          'Drive to Kibale Forest (5-6 hours)',
          'Lunch en route',
          'Check-in at eco-lodge',
          'Evening nature walk',
          'Briefing about chimpanzee tracking',
          'Dinner and overnight',
        ],
      },
      {
        day: 2,
        title: 'Chimpanzee Tracking and Departure',
        activities: [
          'Early breakfast',
          'Chimpanzee tracking (2-4 hours)',
          '1 hour with chimpanzees',
          'Return to lodge',
          'Lunch',
          'Check-out',
          'Return journey',
          'Drop-off',
        ],
      },
    ],
    costBreakdown: {
      included: [
        'Chimpanzee tracking permit ($200)',
        'Accommodation (1 night)',
        'All meals',
        'Transportation',
        'Professional guide',
        'Park fees',
      ],
      excluded: [
        'International flights',
        'Visa fees',
        'Travel insurance',
        'Tips',
        'Personal expenses',
      ],
    },
  },
  {
    id: 'rwenzori-mountains',
    title: 'Rwenzori Mountains Hike',
    destination: 'Rwenzori Mountains National Park',
    duration: '5 Days / 4 Nights',
    price: 'From $800 per person',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop',
    description: 'Conquer the "Mountains of the Moon" - Africa\'s third highest peak. Experience stunning alpine scenery, unique flora, and challenging mountain terrain.',
    highlights: [
      'Mountain climbing',
      'Scenic views',
      'Camping accommodation',
      'Professional mountain guides',
      'Porters included',
    ],
    type: 'domestic',
    category: 'Adventure',
    itinerary: [
      {
        day: 1,
        title: 'Arrival and Start of Trek',
        activities: [
          'Pickup from Kasese',
          'Transfer to park headquarters',
          'Briefing and equipment check',
          'Start trek to Nyabitaba Hut',
          'Camping and dinner',
        ],
      },
      {
        day: 2,
        title: 'Ascend to John Matte Hut',
        activities: [
          'Early breakfast',
          'Continue ascent',
          'Cross Bujuku River',
          'Reach John Matte Hut',
          'Camping and dinner',
        ],
      },
      {
        day: 3,
        title: 'Reach Bujuku Lake',
        activities: [
          'Breakfast',
          'Trek to Bujuku Lake',
          'Scenic views of glaciers',
          'Camping at Bujuku Hut',
          'Dinner',
        ],
      },
      {
        day: 4,
        title: 'Summit Attempt',
        activities: [
          'Early morning summit attempt',
          'Reach Margherita Peak (5,109m)',
          'Descend to Kitandara Hut',
          'Camping and dinner',
        ],
      },
      {
        day: 5,
        title: 'Descent and Departure',
        activities: [
          'Breakfast',
          'Final descent',
          'Return to park headquarters',
          'Certificate presentation',
          'Transfer back',
        ],
      },
    ],
    costBreakdown: {
      included: [
        'Park entry fees',
        'Mountain climbing permit',
        'Camping accommodation',
        'All meals',
        'Professional guides',
        'Porters',
        'Camping equipment',
      ],
      excluded: [
        'Personal hiking gear',
        'International flights',
        'Visa fees',
        'Travel insurance',
        'Tips',
        'Personal expenses',
      ],
    },
  },
  {
    id: 'source-of-nile',
    title: 'Source of the Nile Tour',
    destination: 'Jinja',
    duration: '2 Days / 1 Night',
    price: 'From $300 per person',
    image: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1200&h=800&fit=crop',
    description: 'Visit the source of the world\'s longest river and enjoy water activities including white-water rafting, kayaking, and boat cruises.',
    highlights: [
      'Source of the Nile visit',
      'Water activities',
      'Hotel accommodation',
      'Boat cruise',
      'Adventure activities',
    ],
    type: 'domestic',
    category: 'Adventure',
    itinerary: [
      {
        day: 1,
        title: 'Journey to Jinja',
        activities: [
          'Pickup from Kampala',
          'Drive to Jinja (2-3 hours)',
          'Visit Source of the Nile',
          'Boat cruise',
          'Lunch',
          'Check-in at hotel',
          'Optional: White-water rafting',
          'Dinner and overnight',
        ],
      },
      {
        day: 2,
        title: 'Activities and Departure',
        activities: [
          'Breakfast',
          'Kayaking or bungee jumping',
          'Lunch',
          'Check-out',
          'Return journey to Kampala',
          'Drop-off',
        ],
      },
    ],
    costBreakdown: {
      included: [
        'Accommodation (1 night)',
        'All meals',
        'Source of the Nile visit',
        'Boat cruise',
        'Transportation',
        'Guide services',
      ],
      excluded: [
        'White-water rafting ($125)',
        'Bungee jumping ($50)',
        'Kayaking ($40)',
        'International flights',
        'Tips',
        'Personal expenses',
      ],
    },
  },
  // International Tours
  {
    id: 'dubai-city-break',
    title: 'Dubai City Break',
    destination: 'Dubai, UAE',
    duration: '5 Days / 4 Nights',
    price: 'From $1,200 per person',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&h=800&fit=crop',
    description: 'Explore the modern marvels of Dubai with our curated city tour. Experience luxury shopping, stunning architecture, and desert adventures.',
    highlights: [
      'Burj Khalifa visit',
      'Desert safari',
      'Shopping tours',
      'Luxury hotels',
      'Dhow cruise',
    ],
    type: 'international',
    category: 'City Tour',
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Dubai',
        activities: [
          'Airport pickup',
          'Transfer to hotel',
          'Check-in',
          'Evening Dhow cruise with dinner',
          'Overnight at hotel',
        ],
      },
      {
        day: 2,
        title: 'City Tour and Burj Khalifa',
        activities: [
          'Breakfast at hotel',
          'Dubai city tour',
          'Visit Burj Khalifa (124th floor)',
          'Dubai Mall visit',
          'Lunch',
          'Evening at leisure',
          'Overnight',
        ],
      },
      {
        day: 3,
        title: 'Desert Safari',
        activities: [
          'Breakfast',
          'Morning at leisure',
          'Afternoon desert safari',
          'Camel riding',
          'BBQ dinner and entertainment',
          'Return to hotel',
        ],
      },
      {
        day: 4,
        title: 'Shopping and Leisure',
        activities: [
          'Breakfast',
          'Shopping at Gold Souk and Spice Souk',
          'Dubai Marina visit',
          'Lunch',
          'Palm Jumeirah tour',
          'Evening at leisure',
        ],
      },
      {
        day: 5,
        title: 'Departure',
        activities: [
          'Breakfast',
          'Check-out',
          'Transfer to airport',
          'Departure',
        ],
      },
    ],
    costBreakdown: {
      included: [
        'Return flights (from Entebbe)',
        'Hotel accommodation (4 nights)',
        'Daily breakfast',
        'Dhow cruise dinner',
        'Desert safari',
        'Burj Khalifa tickets',
        'City tour',
        'Airport transfers',
      ],
      excluded: [
        'Visa fees',
        'Lunch and dinner (except specified)',
        'Travel insurance',
        'Tips',
        'Personal expenses',
        'Shopping',
      ],
    },
  },
  {
    id: 'paris-london',
    title: 'Paris & London',
    destination: 'Paris, France & London, UK',
    duration: '7 Days / 6 Nights',
    price: 'From $2,500 per person',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&h=800&fit=crop',
    description: 'Experience two of Europe\'s most iconic cities. From the Eiffel Tower to Big Ben, discover the best of Paris and London.',
    highlights: [
      'Eiffel Tower visit',
      'Louvre Museum',
      'Big Ben and Westminster',
      'Thames River cruise',
      'Eurostar train journey',
    ],
    type: 'international',
    category: 'City Tour',
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Paris',
        activities: [
          'Airport pickup',
          'Transfer to hotel',
          'Check-in',
          'Evening Seine River cruise',
          'Dinner',
          'Overnight',
        ],
      },
      {
        day: 2,
        title: 'Paris City Tour',
        activities: [
          'Breakfast',
          'Eiffel Tower visit',
          'Louvre Museum',
          'Lunch',
          'Notre-Dame Cathedral',
          'Champs-Élysées walk',
          'Dinner',
        ],
      },
      {
        day: 3,
        title: 'Versailles and More',
        activities: [
          'Breakfast',
          'Day trip to Palace of Versailles',
          'Lunch',
          'Return to Paris',
          'Evening at leisure',
        ],
      },
      {
        day: 4,
        title: 'Travel to London',
        activities: [
          'Breakfast',
          'Check-out',
          'Eurostar to London',
          'Hotel check-in',
          'Evening Thames cruise',
          'Dinner',
        ],
      },
      {
        day: 5,
        title: 'London City Tour',
        activities: [
          'Breakfast',
          'Big Ben and Westminster',
          'Buckingham Palace',
          'Tower of London',
          'Lunch',
          'British Museum',
          'Dinner',
        ],
      },
      {
        day: 6,
        title: 'London Exploration',
        activities: [
          'Breakfast',
          'Hyde Park',
          'Shopping at Oxford Street',
          'Lunch',
          'London Eye',
          'Evening show (optional)',
        ],
      },
      {
        day: 7,
        title: 'Departure',
        activities: [
          'Breakfast',
          'Check-out',
          'Transfer to airport',
          'Departure',
        ],
      },
    ],
    costBreakdown: {
      included: [
        'Return flights (from Entebbe)',
        'Hotel accommodation (6 nights)',
        'Daily breakfast',
        'Eurostar tickets',
        'City tours',
        'Museum entries',
        'Airport transfers',
      ],
      excluded: [
        'Schengen visa',
        'UK visa',
        'Lunch and dinner',
        'Travel insurance',
        'Tips',
        'Personal expenses',
      ],
    },
  },
  {
    id: 'cape-town',
    title: 'Cape Town Adventure',
    destination: 'Cape Town, South Africa',
    duration: '6 Days / 5 Nights',
    price: 'From $1,800 per person',
    image: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=1200&h=800&fit=crop',
    description: 'Discover the beauty of Cape Town - from Table Mountain to wine country, penguin beaches to safari adventures.',
    highlights: [
      'Table Mountain',
      'Wine tours',
      'Penguin Beach',
      'Safari experience',
      'Cape of Good Hope',
    ],
    type: 'international',
    category: 'Adventure',
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Cape Town',
        activities: [
          'Airport pickup',
          'Transfer to hotel',
          'Check-in',
          'V&A Waterfront visit',
          'Dinner',
          'Overnight',
        ],
      },
      {
        day: 2,
        title: 'Table Mountain and City Tour',
        activities: [
          'Breakfast',
          'Table Mountain cable car',
          'City tour',
          'Lunch',
          'Robben Island tour',
          'Dinner',
        ],
      },
      {
        day: 3,
        title: 'Cape Peninsula Tour',
        activities: [
          'Breakfast',
          'Cape of Good Hope',
          'Boulders Beach (Penguins)',
          'Lunch',
          'Chapman\'s Peak Drive',
          'Return to hotel',
        ],
      },
      {
        day: 4,
        title: 'Wine Country',
        activities: [
          'Breakfast',
          'Stellenbosch wine tour',
          'Wine tasting',
          'Lunch at vineyard',
          'Return to Cape Town',
          'Dinner',
        ],
      },
      {
        day: 5,
        title: 'Safari Day Trip',
        activities: [
          'Early breakfast',
          'Full-day safari experience',
          'Lunch',
          'Wildlife viewing',
          'Return to hotel',
          'Dinner',
        ],
      },
      {
        day: 6,
        title: 'Departure',
        activities: [
          'Breakfast',
          'Check-out',
          'Transfer to airport',
          'Departure',
        ],
      },
    ],
    costBreakdown: {
      included: [
        'Return flights (from Entebbe)',
        'Hotel accommodation (5 nights)',
        'Daily breakfast',
        'Table Mountain tickets',
        'Wine tour',
        'Safari experience',
        'All tours',
        'Airport transfers',
      ],
      excluded: [
        'Visa fees',
        'Lunch and dinner',
        'Travel insurance',
        'Tips',
        'Personal expenses',
      ],
    },
  },
  {
    id: 'thailand-discovery',
    title: 'Thailand Discovery',
    destination: 'Bangkok & Phuket, Thailand',
    duration: '8 Days / 7 Nights',
    price: 'From $1,500 per person',
    image: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=1200&h=800&fit=crop',
    description: 'Experience the best of Thailand - from bustling Bangkok temples to pristine Phuket beaches.',
    highlights: [
      'Bangkok temples',
      'Beach resorts',
      'Floating markets',
      'Elephant sanctuary',
      'Thai cooking class',
    ],
    type: 'international',
    category: 'Beach & Culture',
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Bangkok',
        activities: [
          'Airport pickup',
          'Transfer to hotel',
          'Check-in',
          'Evening street food tour',
          'Overnight',
        ],
      },
      {
        day: 2,
        title: 'Bangkok Temples',
        activities: [
          'Breakfast',
          'Grand Palace',
          'Wat Pho (Reclining Buddha)',
          'Wat Arun',
          'Lunch',
          'Floating market',
          'Dinner',
        ],
      },
      {
        day: 3,
        title: 'Bangkok to Phuket',
        activities: [
          'Breakfast',
          'Check-out',
          'Flight to Phuket',
          'Hotel check-in',
          'Beach time',
          'Dinner',
        ],
      },
      {
        day: 4,
        title: 'Phuket Beach Day',
        activities: [
          'Breakfast',
          'Beach activities',
          'Water sports',
          'Lunch',
          'Spa treatment',
          'Dinner',
        ],
      },
      {
        day: 5,
        title: 'Island Hopping',
        activities: [
          'Breakfast',
          'Phi Phi Islands tour',
          'Snorkeling',
          'Lunch',
          'Beach time',
          'Return to hotel',
        ],
      },
      {
        day: 6,
        title: 'Elephant Sanctuary',
        activities: [
          'Breakfast',
          'Elephant sanctuary visit',
          'Thai cooking class',
          'Lunch',
          'Return to hotel',
          'Dinner',
        ],
      },
      {
        day: 7,
        title: 'Phuket to Bangkok',
        activities: [
          'Breakfast',
          'Check-out',
          'Flight to Bangkok',
          'Hotel check-in',
          'Shopping',
          'Farewell dinner',
        ],
      },
      {
        day: 8,
        title: 'Departure',
        activities: [
          'Breakfast',
          'Check-out',
          'Transfer to airport',
          'Departure',
        ],
      },
    ],
    costBreakdown: {
      included: [
        'Return flights (from Entebbe)',
        'Domestic flights',
        'Hotel accommodation (7 nights)',
        'Daily breakfast',
        'All tours',
        'Elephant sanctuary',
        'Cooking class',
        'Airport transfers',
      ],
      excluded: [
        'Visa fees',
        'Lunch and dinner',
        'Travel insurance',
        'Tips',
        'Personal expenses',
      ],
    },
  },
];

export interface ItineraryDay {
  day: number;
  title: string;
  activities: string[];
}

export interface CostBreakdown {
  included: string[];
  excluded: string[];
}

export interface TourPackageWithDetails extends TourPackage {
  itinerary: ItineraryDay[];
  costBreakdown: CostBreakdown;
}

